### ISSUE TITLE
I had a problem replicating the code.

### ISSUE THREAD

**Issue by wangqinxuan** [Kearlay/research#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/pycharm-project/research-master/py/eeg_main.py", line 10, in <module>
    from eeg_import import get_data, FNAMES
  File "D:\pycharm-project\research-master\py\eeg_import.py", line 156, in <module>
    a,b=get_data(subj_num=FNAMES, epoch_sec=0.0625)
  File "D:\pycharm-project\research-master\py\eeg_import.py", line 151, in get_data
    X = np.stack(X)
  File "D:\Program Files\pycharm2017\anaconda2\envs\py3.6\lib\site-packages\numpy\core\shape_base.py", line 350, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by wangqinxuan** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/pycharm-project/research-master/py/eeg_main.py", line 25, in <module>
    get_data(FNAMES, epoch_sec=0.0625)
  File "D:\pycharm-project\research-master\py\eeg_import.py", line 151, in get_data
    X = np.stack(X)
  File "D:\Program Files\pycharm2017\anaconda2\envs\py3.6\lib\site-packages\numpy\core\shape_base.py", line 350, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by mabusdogma** [comment]
from
`events = raw.find_edf_events()`

change to
`events = mne.events_from_annotations(raw)`

or install an earlier version of mne
!pip mne==0.18

after that, you can have another error:
```

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_1744\371453340.py in <module>
----> 1 X,y = get_data(FNAMES, epoch_sec=0.0625)

~\AppData\Local\Temp\ipykernel_1744\515908294.py in get_data(subj_num, epoch_sec)
    126 
    127                 for i, event in enumerate(events):
--> 128                     X, y = append_X_Y(run_type=1, event=event, old_x=X, old_y=y, data=data)
    129 
    130             # run 6,10,14 - imagine opening and closing both fists or both feet

~\AppData\Local\Temp\ipykernel_1744\515908294.py in append_X_Y(run_type, event, old_x, old_y, data)
     56         Then assign X and Y according to the event types'''
     57         # Number of sliding windows
---> 58         n_segments = int(event[1]/epoch_sec)
     59 
     60         # Rest excluded

TypeError: only size-1 arrays can be converted to Python scalars
```

This is when I'm stucked on right now
